sudo: required
language: c
services:
  - docker
script: |
  docker run -ti --rm --privileged -w /build -v `pwd`:/build \
    -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
    fedora:24 \
    /bin/bash -c 'dnf install -y curl dbus make sudo systemd-container tar unzip && dbus-uuidgen --ensure=/etc/machine-id && make'
deploy:
  provider: releases
  api_key:
    secure: LzLM/6UWIFAODXVOYWKfBzcQMkNktRNp2vWdklE5PGTFYhap/iCqN3/9QUjsV8zAg1WsYU6zXlGsUq9oiDEaNq3cUpMNUtqURp2Y0BbuTyg+u+f93w/3Yi/tzPiLdbSHmT2RaxXSibrjPS32ZMP8MixRB4Xrtc7Pon/7eZSAdURBAq+B8um48E1Zyybf8REpCgkcAsJyiqhQxLWS3ekdfXoIhbUib5YDJdwKbMzwYzI22lVg7qI9g/6rS6qX+faFMH9Jztve7KbxOVjkYYXZ4PsUw1Abo2Tas7HxG67tM+6/jNGYryYBinhsKVMmrgbAlPRubqCdJeUeFgeaby66QEHSi35cHaiqkk+SujclJ5b9StfYFRhLCWkerkRulYCW6wecYWhAPMGaNbaRUJOsyG4nNoVPpHhszmHcKSrI9IWhqhl2wnNGyYC9guWDUYrb1eW8/sCWRvhYDtRzecHMhWTOX179ZDH14v9cLQL3G20F7JDxhFDA3ej33Wamro1Cee5gEUL6cHkBrJzbcJDLz+3XJcikm2FEbgL96Kq6eYehg7PnSiZhIeZKACYdTNDo7kpq0OC9ZmEO8fX+L61typO8AKtWbFbRrzH7x51nYh0HfMXWP7VoPo4/czTbGUinJ6b+JD/Fybx3w9x64q/RHm88iSnebyB81ekmshmbM64=
  file: dist/dit4c-router-ngrok2.aci
  on:
    repo: dit4c/dit4c-router-ngrok2
